### ISSUE TITLE
Let's do a little refactoring

### ISSUE THREAD

**Issue by vasayxtx** [mikhsol/maze-problem#2]
+ Why `__init__` of `MazeSolver` has default value for `maze` argument?
+ It would be better to define start and end chars as const.
+ `_check_position` is bad name for his behaviour.  It does not check anything.
+ Actually, you don't need to store `value` in the `Node` object.
+ PEP8 is not met.
+ Type hinting is good thing to improve the readability of the code. Let's use it.

Could you please create PR with changes.

**Comment by mikhsol** [comment]
> Why __init__ of MazeSolver has a default value for maze argument?

I provide a default value as an empty tuple to not catch IndexError exception in "_find_init_node" method which calls after maze initialization. You right here, it has no sense to create solver class without provided maze in such design. A better solution will check if the maze is None and raise a proper exception. Done.

> It would be better to define start and end chars as const.

Agree, done.

>`_check_position` is a bad name for his behavior. It does not check anything.

Agree, `_get_next_node` think will fit better. Done.

> Actually, you don't need to store a value in the Node object.

Do not think so. I use it to construct the final path. Of cause I can just take a value from a maze (in this method) and it will save some memory, but here I think working explicitly with node make the code more readable.

> PEP8 is not met.

Fix.

> Type hinting is a good thing to improve the readability of the code. Let's use it.

Ok, yes, it does a code more readable, but it does not reflect the dynamic nature of python. To be sure you have no problems with types in dynamic languages you write unit tests. Anyway, I add type hinting.

Commit ac4c09dd.
